import{S as a,N as u,K as p,M as d,a as w}from"./assets/vendor-CCySa_t8.js";(function(){const o=document.createElement("link").relList;if(o&&o.supports&&o.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))s(e);new MutationObserver(e=>{for(const n of e)if(n.type==="childList")for(const c of n.addedNodes)c.tagName==="LINK"&&c.rel==="modulepreload"&&s(c)}).observe(document,{childList:!0,subtree:!0});function r(e){const n={};return e.integrity&&(n.integrity=e.integrity),e.referrerPolicy&&(n.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?n.credentials="include":e.crossOrigin==="anonymous"?n.credentials="omit":n.credentials="same-origin",n}function s(e){if(e.ep)return;e.ep=!0;const n=r(e);fetch(e.href,n)}})();const g=document.querySelector(".projects-swiper-next-button"),v=document.querySelector(".projects-swiper-prev-button");new a(".swiper-projects-container",{modules:[u,p,d],navigation:{nextEl:g,prevEl:v},spaceBetween:100,slidesPerView:1,speed:800,keyboard:{enabled:!0,onlyInViewport:!0},mousewheel:{forceToAxis:!0},touchEventsTarget:"wrapper",createElements:!0});const l=document.querySelectorAll(".js-covers__inner"),f=document.querySelector(".container_covers");window.addEventListener("scroll",y);const i=f.offsetHeight;function y(){for(let t=0;t<l.length;t++){const o=l[t];let r=window.innerHeight;const s=h(f).top;let e=r-i/5;i>r&&(r=r-r/5),pageYOffset>s-e&&pageYOffset<s+i?o.classList.replace("visually-hidden","covers__inner"):o.classList.replace("covers__inner","visually-hidden"),pageYOffset>s+(i-100)&&o.classList.replace("covers__inner","visually-hidden")}}function h(t){const o=t.getBoundingClientRect(),r=window.pageXOffset||document.documentElement.scrollLeft,s=window.pageYOffset||document.documentElement.scrollTop;return{top:o.top+s,left:o.left+r}}const m=document.querySelector(".section-reviews .swiper-wrapper"),b="https://portfolio-js.b.goit.study/api/reviews",E=document.querySelector(".swiper-next-buttonn"),L=document.querySelector(".swiper-prev-buttonn");async function S(){try{const{data:t}=await w(b,{headers:{"Content-Type":"application/json"}});return t}catch(t){console.error("Error reviews:",t.message),m.innerHTML=O()}}function O(){return`
    <div class="swiper-slide error">
      <p class="glush-reviews">Not found</p>
    </div>
  `}S().then(t=>{console.log(t),m.innerHTML=x(t)}).catch(t=>{console.error(t)});function x(t){return t.map(({id:o,author:r,avatar_url:s,review:e})=>`
        <li class="list-item swiper-slide">
          <img src="${s}" alt="${r}" class="author-item-img" />
          <h3 class="author-name">${r}</h3>
          <p class="reviews-descreiption">${e}</p>
        </li>`).join("")}new a(".swiper",{modules:[u,p,d],navigation:{nextEl:E,prevEl:L},loop:!1,spaceBetween:16,slidesPerView:1,speed:800,breakpoints:{768:{slidesPerView:2},1440:{slidesPerView:4}},keyboard:{enabled:!0,onlyInViewport:!0},mousewheel:{forceToAxis:!0},touchEventsTarget:"container",createElements:!0});
//# sourceMappingURL=index.js.map
